# CMake generated Testfile for 
# Source directory: /Volumes/Work/projects/code/pqc-hsm-fpga
# Build directory: /Volumes/Work/projects/code/pqc-hsm-fpga/build-host
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[util]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_util")
set_tests_properties([=[util]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;319;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[hwrng]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_hwrng")
set_tests_properties([=[hwrng]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;320;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[selftest]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_selftest")
set_tests_properties([=[selftest]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;321;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_parse]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_kat_parse")
set_tests_properties([=[kat_parse]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;322;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[pqc_meta]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_pqc_meta")
set_tests_properties([=[pqc_meta]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;323;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[pqc_roundtrip]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_pqc_roundtrip")
set_tests_properties([=[pqc_roundtrip]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;324;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[pqc_hw]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_pqc_hw")
set_tests_properties([=[pqc_hw]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;325;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kdf]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_kdf")
set_tests_properties([=[kdf]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;326;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[slot_fsm]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_slot_fsm")
set_tests_properties([=[slot_fsm]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;327;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[slot_meta]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_slot_meta")
set_tests_properties([=[slot_meta]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;328;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[slot]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_slot")
set_tests_properties([=[slot]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;329;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[slot_concurrent]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_slot_concurrent")
set_tests_properties([=[slot_concurrent]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;330;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[crypto_concurrent]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_crypto_concurrent")
set_tests_properties([=[crypto_concurrent]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;331;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[profile_no_stub_kdr]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_profile.sh")
set_tests_properties([=[profile_no_stub_kdr]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;333;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[wrap]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_wrap")
set_tests_properties([=[wrap]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;335;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[keystore]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_keystore")
set_tests_properties([=[keystore]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;336;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[shamir]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_shamir")
set_tests_properties([=[shamir]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;337;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[backup]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_backup")
set_tests_properties([=[backup]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;338;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[zeroize]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_zeroize")
set_tests_properties([=[zeroize]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;339;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ct_timing]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_ct_timing")
set_tests_properties([=[ct_timing]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;340;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[audit]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_audit")
set_tests_properties([=[audit]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;341;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kdr]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_kdr")
set_tests_properties([=[kdr]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;342;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[proto]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_proto")
set_tests_properties([=[proto]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;343;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[inject]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_inject")
set_tests_properties([=[inject]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;344;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[cross_world]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_cross_world")
set_tests_properties([=[cross_world]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;345;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[p11]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_p11")
set_tests_properties([=[p11]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;346;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[fuzz]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/fuzz_standalone" "4000")
set_tests_properties([=[fuzz]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;350;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ntt_oracle]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/hardware/model/ntt_oracle.py")
set_tests_properties([=[ntt_oracle]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;357;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[rtl_sim]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/rtl_sim.sh")
set_tests_properties([=[rtl_sim]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;365;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[prim_count]=] "python3" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/prim_count.py" "--self-test")
set_tests_properties([=[prim_count]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;368;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[tls_regress]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/tls_regress.sh")
set_tests_properties([=[tls_regress]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;373;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[shell_var_braces]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_shell_vars.py")
set_tests_properties([=[shell_var_braces]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;376;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[daemon_failclosed]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/daemon_failclosed.sh" "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host")
set_tests_properties([=[daemon_failclosed]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;379;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[cli_smoke]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/cli_smoke.sh" "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host")
set_tests_properties([=[cli_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;382;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[accel]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_accel")
set_tests_properties([=[accel]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;385;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[accel_axi]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_accel_axi")
set_tests_properties([=[accel_axi]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;386;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[e2e]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_e2e")
set_tests_properties([=[e2e]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;387;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[e2e_p11]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/e2e_p11.sh" "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/pqchsm-pkcs11.dylib")
set_tests_properties([=[e2e_p11]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;389;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[p11_demos]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/demo_p11.sh" "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/pqchsm-pkcs11.dylib")
set_tests_properties([=[p11_demos]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;392;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[p11_smoke]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/p11_smoke.sh" "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/pqchsm-pkcs11.dylib")
set_tests_properties([=[p11_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;395;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[anchor]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_anchor")
set_tests_properties([=[anchor]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;397;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[tee_native]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/tee_native_tests.sh")
set_tests_properties([=[tee_native]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;401;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ta_surface_self_test]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_ta_surface.py" "--self-test")
set_tests_properties([=[ta_surface_self_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;406;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ta_surface]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_ta_surface.py")
set_tests_properties([=[ta_surface]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;408;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kdr_no_readback]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_no_readback.py" "/Volumes/Work/projects/code/pqc-hsm-fpga/include/pqchsm/kdr.h")
set_tests_properties([=[kdr_no_readback]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;415;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ct_audit_self_test]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/ct_audit.py" "--self-test")
set_tests_properties([=[ct_audit_self_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;422;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[ct_audit]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/ct_audit.py")
set_tests_properties([=[ct_audit]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;424;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[zeroize_check_self_test]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_zeroize.py" "--self-test")
set_tests_properties([=[zeroize_check_self_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;428;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[zeroize_check]=] "/opt/homebrew/Frameworks/Python.framework/Versions/3.14/bin/python3.14" "/Volumes/Work/projects/code/pqc-hsm-fpga/tools/check_zeroize.py")
set_tests_properties([=[zeroize_check]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;430;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[audit_integration]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/test_audit_integration")
set_tests_properties([=[audit_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;433;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mlkem_keygen]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mlkem_keygen.kat")
set_tests_properties([=[kat_mlkem_keygen]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mlkem_encaps]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mlkem_encaps.kat")
set_tests_properties([=[kat_mlkem_encaps]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mlkem_decaps]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mlkem_decaps.kat")
set_tests_properties([=[kat_mlkem_decaps]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mldsa_keygen]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mldsa_keygen.kat")
set_tests_properties([=[kat_mldsa_keygen]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mldsa_siggen]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mldsa_siggen.kat")
set_tests_properties([=[kat_mldsa_siggen]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
add_test([=[kat_mldsa_sigver]=] "/Volumes/Work/projects/code/pqc-hsm-fpga/build-host/kat_runner" "/Volumes/Work/projects/code/pqc-hsm-fpga/vectors/mldsa_sigver.kat")
set_tests_properties([=[kat_mldsa_sigver]=] PROPERTIES  _BACKTRACE_TRIPLES "/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;437;add_test;/Volumes/Work/projects/code/pqc-hsm-fpga/CMakeLists.txt;0;")
